
spring:
datasource:
driverClassName: com.mysql.jdbc.Driver
url: jdbc:mysql://localhost:3306/user_entity
username: root
password: Varma@180
jpa:
hibernate.ddl-auto: update
generate-ddl: true
show-sql: true